### ISSUE TITLE
Having an issue running get_devices

### ISSUE THREAD

**Issue by barry99705** [libdyson-wg/libdyson-neon#11]
─$ python3 get_devices.py
Please choose your account region
1: Mainland China
2: Rest of the World
Region [1/2]: 2
Region code: US
Email: XXXXX@gmail.com
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/libdyson-neon/get_devices.py", line 22, in <module>
    verify = account.login_email_otp(email, region)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/libdyson-neon/libdyson/cloud/account.py", line 161, in login_email_otp
    jsonRes = response.json()
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by dotvezz** [comment]
Interesting! This looks like an error on the part of the Dyson API. It should _always_ be valid JSON from the API unless something was misconfigured on the API itself, or in between the API and you.

 I verified the script seems to be working correctly (at least for my particular account, on my machine).

Can you try again and verify whether the issue persists?

**Comment by barry99705** [comment]
Yep, same error.  I'm logged out of the android app, haven't logged back
into it since 11 this morning, so 6ish hours ago.

**Comment by dotvezz** [comment]
Thanks for the confirmation. I wonder if you'd be willing to help figure out what's happening to you. I've got a quick-and-dirty debugging branch for you here if you'd like to switch to it: https://github.com/dotvezz/libdyson-neon/tree/debug-login-json

You can also just edit your files locally, it's just adding a lazy print around `libdyson/cloud/account.py` line 160 to see what the API is giving you.:

```diff
diff --git a/libdyson/cloud/account.py b/libdyson/cloud/account.py
index 0eaa88c..08f84b7 100644
--- a/libdyson/cloud/account.py
+++ b/libdyson/cloud/account.py
@@ -158,6 +158,8 @@ class DysonAccount:
             auth=False,
         )
 
+        print(response.content)
+
         jsonRes = response.json()
 
         account_status = jsonRes["accountStatus"]

```

**Comment by barry99705** [comment]
─$ python3 get_devices.py
Please choose your account region
1: Mainland China
2: Rest of the World
Region [1/2]: 2
Region code: US
Email: ***@***.***
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 971, in
json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525,
in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 372, in
decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 402, in
raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting property name enclosed in
double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/libdyson-neon/get_devices.py", line 22, in <module>
    verify = account.login_email_otp(email, region)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/libdyson-neon/libdyson/cloud/account.py", line 130, in
login_email_otp
    jsonRes = response.json()
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/models.py", line 975, in
json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting property name enclosed in
double quotes: line 1 column 2 (char 1)

**Comment by dotvezz** [comment]
Hmm, something is weird. It doesn't seem to have **_any_** content in the response. Sorry to be a bother, but I'd like to get a bit more information from you.

Can you tell me a bit more about the environment you're running the script in?

- Python Version
- OS Version

And can you run the following two cURL requests and see what it gives you? Make sure to fill in your email address on the last line.

```sh
curl https://appapi.cp.dyson.com/v1/provisioningservice/application/Android/version
curl -H 'Content-Type: application/json; charset=utf-8' \
     -X POST 'https://appapi.cp.dyson.com/v3/userregistration/email/userstatus?country=US' \
     -d '{"email":"YOUR_EMAIL_HERE"}'
```

The first request primes the API to respond to the next request, it's explained in more depth [here](https://github.com/libdyson-wg/libdyson-neon/blob/main/libdyson/cloud/account.py#L122-L135).

The second request checks the account status with your email address. It's the request that you're currently erroring out on, and which seems to be giving an empty response content.

**Comment by barry99705** [comment]
The script has worked in the past.  I just replaced my router and the HA
plugin quit working on a couple of my devices, but rebooting them fixed
them.  Just the fan didn't come back.  Saw someone else had that issue and
removed and readded the fan fixed it.

Kali linux

$ uname -a
Linux TheGibson 6.1.0-kali7-amd64 #1 SMP PREEMPT_DYNAMIC Debian
6.1.20-2kali1 (2023-04-18) x86_64 GNU/Linux

Python 3.11.2

┌──(kali㉿TheGibson)-[~/libdyson-neon]
└─$ curl https://appapi.cp.dyson.com/v1/provisioningservice/application/Android/version
"5.0.21061"


┌──(kali㉿TheGibson)-[~/libdyson-neon]
└─$ curl -H 'Content-Type: application/json; charset=utf-8' \
     -X POST 'https://appapi.cp.dyson.com/v3/userregistration/email/userstatus?country=US'
\
     -d ***@***.***"}'
{"accountStatus":"ACTIVE","authenticationMethod":"EMAIL_PWD_2FA"}

**Comment by barry99705** [comment]
WAIT!  It's working now...

**Comment by dotvezz** [comment]
Yay! I don't think I can claim to have done anything to help you, and I wish we knew what was going on. But I'm glad things are working! I'll go ahead and close this, but feel free to follow up here if you have any more issues.

My takeaways:

1. Make some easier way to debug things
     - Env var?
     - Command line flag?
     - Config file
     - Any of the above?

**Comment by ygrpos** [comment]
I was getting the same error and I finally figured it out - I wasn't capitalizing the country code...

**Comment by KurtaPajama** [comment]
Unfortunately I am getting this error now. The file worked the first time for me, but I wasn't quick enough to get the code sent to my email. I copied the code from my email and tried pasting it in but it didn't work. I restarted the get_devices and this is the error I'm getting now.

1: Mainland China
2: Rest of the World
Region [1/2]: 2
Region code: US
Email: xxx@xxx.xxx
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\libdyson-neon-main\libdyson-neon-main\get_devices.py", line 22, in <module>
    verify = account.login_email_otp(email, region)
  File "C:\Users\xxx\Downloads\libdyson-neon-main\libdyson-neon-main\libdyson\cloud\account.py", line 161, in login_email_otp
    jsonRes = response.json()
  File "C:\Python\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting property name enclosed in double quotes] {error: "Endpoint is not available currently"}: 1

C:\Users\xxx\Downloads\libdyson-neon-main\libdyson-neon-main>


Seems like for the other user Barry99705, he waited a day, and was able to use get_devices.

**Comment by KurtaPajama** [comment]
> Unfortunately I am getting this error now. The file worked the first time for me, but I wasn't quick enough to get the code sent to my email. I copied the code from my email and tried pasting it in but it didn't work. I restarted the get_devices and this is the error I'm getting now.
> 
> 1: Mainland China 2: Rest of the World Region [1/2]: 2 Region code: US Email: [xxx@xxx.xxx](mailto:xxx@xxx.xxx) Traceback (most recent call last): File "C:\Python\lib\site-packages\requests\models.py", line 910, in json return complexjson.loads(self.text, **kwargs) File "C:\Python\lib\json__init__.py", line 346, in loads return _default_decoder.decode(s) File "C:\Python\lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "C:\Python\lib\json\decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\xxx\Downloads\libdyson-neon-main\libdyson-neon-main\get_devices.py", line 22, in verify = account.login_email_otp(email, region) File "C:\Users\xxx\Downloads\libdyson-neon-main\libdyson-neon-main\libdyson\cloud\account.py", line 161, in login_email_otp jsonRes = response.json() File "C:\Python\lib\site-packages\requests\models.py", line 917, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: [Errno Expecting property name enclosed in double quotes] {error: "Endpoint is not available currently"}: 1
> 
> C:\Users\xxx\Downloads\libdyson-neon-main\libdyson-neon-main>
> 
> Seems like for the other user Barry99705, he waited a day, and was able to use get_devices.

I logged out of the app on my iPhone, and tried to log back in and was getting error "having trouble connecting to Dyson network". I got off WiFi, and the error went away and I was able to log into the app. I tried to run get_devices.py again, and was getting the same error. I hotspotted on my phones 5G (without WiFi), and I was able to retrieve the credentials. Hope this helps someone!
